// FAKE DATA
export const books = [
  {
    id: 1,
    title: "48 Laws of Power",
    summary:
      "Amoral, cunning, ruthless, and instructive, this piercing work distills three thousand years of the history of power in to forty-eight well explicated laws. As attention grabbing in its design as it is in its content, this bold volume outlines the laws of power in their unvarnished essence, synthesizing the philosophies of Machiavelli, Sun-tzu, Carl von Clausewitz, and other great thinkers.",
    url: "https://kbimages1-a.akamaihd.net/a8808e76-9258-4371-a65e-a45e96f5d7ea/1200/1200/False/the-48-laws-of-power-1.jpg",
    originalPrice: 26.95,
    salePrice: null,
    rating: 5,
  },
  {
    id: 2,
    title: "Be Obsessed or be Average",
    summary: `We're in the middle of an epidemic of average. So-called "normal" people get up every day, go to work, do what's asked of them, leave promptly at 5, and return home to sit on the couch and watch TV. Society tells us that this is what it means to lead a balanced life. Don't stress too much or work too hard. Your career isn't everything. But Grant Cardone thinks this preoccupation with balance has really just given an excuse to be mediocre.`,
    url: "https://images-na.ssl-images-amazon.com/images/I/81SbC-kLmXL.jpg",
    originalPrice: 26.5,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Atomic Habits",
    summary: `Learn how to: make time for new habits (even when life gets crazy); overcome a lack of motivation and willpower; design your environment to make success easier; get back on track when you fall off course; ...and much more. Atomic Habits will reshape the way you think about progress and success, and give you the tools and strategies you need to transform your habits--whether you are a team looking to win a championship, an organization hoping to redefine an industry, or simply an individual who wishes to quit smoking, lose weight, reduce stress, or achieve any other goal.`,
    url: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Crack the Coding Interview",
    summary: `Cracking the coding interview is a book written by Gayle Laakmann Mcdowell, an engineer that has worked at companies like Google, Microsoft, and Apple. She holds a B.S. and M.S. in Engineering. The book has 189 programming questions ranging from the most basic of algorithms to the most trickiest.`,
    url: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    originalPrice: 29.95,
    salePrice: 22.95,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Can't Hurt Me",
    summary: `Can’t Hurt Me is the story of David Goggins, who went from being overweight and depressed to becoming a record-breaking athlete, inspiring military leader, and world-class personal trainer.`,
    url: "https://covers.openlibrary.org/b/id/10425061-L.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Deep Work",
    summary: `One of the most valuable skills in our economy is becoming increasingly rare. If you master this skill, you'll achieve extraordinary results. Deep work is the ability to focus without distraction on a cognitively demanding task. It's a skill that allows you to quickly master complicated information and produce better results in less time. Deep work will make you better at what you do and provide the sense of true fulfillment that comes from craftsmanship. In short, deep work is like a super power in our increasingly competitive twenty-first century economy.`,
    url: "https://covers.openlibrary.org/b/id/10088428-L.jpg",
    originalPrice: 32,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 7,
    title: "The 10X Rule",
    summary: `The 10 X Rule unveils the principle of "Massive Action," allowing you to blast through business and risk-aversion while taking concrete steps to reach your dreams. It also demonstrates why people get stuck in the first three actions and how to move into making the 10X Rule a discipline. Find out exactly where to start, what to do, and how to follow up each action you take with more action to achieve Massive Action results. `,
    url: "https://covers.openlibrary.org/b/id/9978588-L.jpg",
    originalPrice: 28,
    salePrice: null,
    rating: 5,
  },
  {
    id: 8,
    title: "Sell Or Be Sold",
    summary: `Sales skills are critical to everyone on the planet. This is because “selling” has a much broader definition than describing the work of someone who works in retail—in fact, selling refers to convincing, influencing, negotiating, and communicating with others, in any arena, to get your way. You have close relationships because you sold other people on spending time with you. You have your health because you sold yourself on diet and exercise. You have a job and money because you sold your boss on your ability.`,
    url: "https://images-na.ssl-images-amazon.com/images/I/81Ibak0tCqL.jpg",
    originalPrice: 38,
    salePrice: 24.5,
    rating: 5,
  },
  {
    id: 9,
    title: "The 33 Strategies of War",
    summary: `New in the bestselling amoral series—a brilliant distillation of the strategies of war that can help us gain mastery in the modern worldRobert Greene's groundbreaking guides, The 48 Laws of Power and The Art of Seduction, espouse profound, timeless less`,
    url: "https://images-na.ssl-images-amazon.com/images/I/313pWTIY6CL.jpg",
    originalPrice: 24.95,
    salePrice: 20.5,
    rating: 4.5,
  },
  {
    id: 10,
    title: "The Art of Seduction",
    summary: `This mesmerizing exploration of the most subtle, elusive, and effective form of power is a masterful analysis of civilization's greatest seducers, from Cleopatra to JFK, as well as the classic literature of seduction from Freud to Kierkegaard and Ovid to Casanova. Robert Greene once again identifies the rules of a timeless, amoral game and explores how to cast a spell, break down resistance, and, ultimately, compel a target to surrender. The Art of Seduction is an indispensable primer of persuasion that reveals the timeless power of this age-old art.`,
    url: "https://m.media-amazon.com/images/I/31dNVIuxgzL.jpg",
    originalPrice: 28.95,
    salePrice: 22.5,
    rating: 4.5,
  },
  {
    id: 11,
    title: "Mastery",
    summary: `Mastery debunks the myth of talent and shows you there are proven steps you can take to achieve mastery in a discipline of your own choosing, by analyzing the paths of some history’s most famous masters, such as Einstein, Darwin and Da Vinci.`,
    url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
    originalPrice: 18.95,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 12,
    title: "Rich Dad Poor Dad",
    summary: `Rich Dad Poor Dad is about Robert Kiyosaki (author) and his two dads — his real father (poor dad) and the father of his best friend (rich dad) — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you do not need to earn a high income to become rich`,
    url: "https://covers.openlibrary.org/b/id/2380224-L.jpg",
    originalPrice: 18,
    salePrice: 16,
    rating: 4.5,
  },
  {
    id: 13,
    title: "Cashflow Quadrant",
    summary: `Do you work increasingly long hours with nothing to show for it, or struggle to have enough left to save after all the bills? Robert Kiyosaki, author of the viral book Rich Dad Poor Dad, explains how anyone can move to the other side of the Cashflow Quadrant and flourish with financial independence as a business owner or investor. `,
    url: "https://covers.openlibrary.org/b/id/1954899-L.jpg",
    originalPrice: 23.5,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 14,
    title: "The 5 Second Rule",
    summary: `The 5 Second Rule is a simple tool that undercuts most of the psychological weapons your brain employs to keep you from taking action, which will allow you to procrastinate less, live happier and reach your goals.`,
    url: "https://covers.openlibrary.org/b/id/8114155-L.jpg",
    originalPrice: 15.95,
    salePrice: null,
    rating: 4,
  },
  {
    id: 15,
    title: "The Millionaire Booklet",
    summary: `The Millionaire Booklet was created for you to keep close to you until you become a millionaire. The eight steps Grant lays out are in a very simple-to-understand language that will allow you to get started today in creating the money you deserve. Let's face it, your parents didn't teach you how to get rich and the schools and colleges don't even talk about it. At a time when more and more people are slipping out of the middle class into poverty, more people are becoming rich.`,
    url: "https://m.media-amazon.com/images/I/415y2rPKvjL.jpg",
    originalPrice: 19.5,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 16,
    title: "Your Next Five Moves",
    summary: `The founder of Valuetainment, Patrick Bet-David, puts together his concepts of strategies and ideas in an easy-to-follow mythology for how anyone can learn to think like an entrepreneur in their career. With a key emphasis on always thinking and planning ‘Five Moves Ahead’ in your current role. `,
    url: "https://images-na.ssl-images-amazon.com/images/I/71A6eUQrhPL.jpg",
    originalPrice: 16.3,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 17,
    title: "How to Win Friends & Influence People",
    summary: `How to Win Friends and Influence People by Dale Carnegie is a self-help classic that reads as a life manual. The core idea is that you can change other people’s behavior simply by changing your own. It teaches you the principles to better understand people, become a more likable person, improve relationships, win others over, and influence behavior through leadership.`,
    url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
    originalPrice: 21.5,
    salePrice: 18.5,
    rating: 4,
  },
];
